/**
 * Covid-19 Sniffer
 * This documentation was created to help developers use the Covid 19 Sniffer Resource.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Body (
  name: String,
  email: String,
  password: String,
  dob: Option[String] = None,
  /* Gender can be either MALE or FEMALE */
  gender: Option[String] = None,
  phone: String,
  profilePhotoUrl: Option[String] = None,
  stateOfResidence: String,
  organization: Boolean
) extends ApiModel


